
version: "3.7"

services:

  nginx-proxy:
    image: "jwilder/nginx-proxy:alpine"
    container_name: "nginx-proxy"
    volumes:
      - "conf:/etc/nginx/conf.d"
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs:ro"
    restart: "always"    
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "net"

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: "letsencrypt-helper"
    volumes_from:
      - "nginx-proxy"
    volumes:
      - "certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      DEFAULT_EMAIL: "tom@tomaaato.xyz"
    restart: "always"

volumes:
  conf:
  certs:
  html:
  vhost:
  dhparam:


networks:
  net:
    external: true
