
version: "3.7"

services:

  nginx-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx-proxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
    restart: "always"    
    ports:
      - "81:80"
    networks:
      - "net"


volumes:
  html:
  vhost:


networks:
  net:
    external: true
